inlivedev/inlive-room

- .dockerignore
- Dockerfile
- next.config.js
Enable docker for this project
> feat: enable docker

- cloudbuild.yaml
This will use Cloudbuild to automatically build the container and pass the env to the build environment
> feat: use cloudbuild

- .dockerignore
- Dockerfile
- cloudbuild.yaml
- package-lock.json
- package.json
This PR fixed and optimized the build and deployment processes.
- Optimized the docker image size
- Fixed env couldn't be used on the cloud build process
> fix: fix build and deployment processes

- app/(pages)/room/[roomId]/page.tsx
- app/_features/home/components/cta.tsx
- app/_features/home/components/join.tsx
- app/_features/room/components/room-actions-bar.tsx
- app/_features/room/components/room-container.tsx
- app/_features/room/components/room-layout.tsx
- app/_features/room/modules/factory.ts
- app/_features/room/modules/media.ts
- app/_features/room/modules/room.ts
This PR mostly focuses on the code and logic refactoring.
> refactor: code refactoring

- .env.local.example
- app/_features/home/create-room/use-create-room.ts
- app/_features/room/components/room-container.tsx
- app/_shared/components/analytics/mixpanel.tsx
- app/layout.tsx
- cloudbuild.yaml
- package-lock.json
- package.json
This PR adds the basic mixpanel integration. The tracking on this integration is solely to understand the usage of this website by listening to specific events.
> feat: mixpanel integration

- README.md
- app/_features/home/footer/footer.tsx
This PR will update the project information on:
- Homepage footer
- Readme
> feat: update project information

- .env.local.example
- .gitignore
- app/error.tsx
- cloudbuild.yaml
- next.config.js
- package-lock.json
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
This PR adds the Sentry error monitoring integration to the project.
Resolves #23
> feat: sentry integration

- README.md
This PR adds more explanation in the readme file about how to use the live website.
> docs: how to use live website

- app/(pages)/room/[roomId]/not-found.tsx
- app/_shared/components/errors/http-error.tsx
- app/not-found.tsx
This PR adds the default 404 UI component to give the user better error information.
> feat: 404 pages

- app/_shared/utils/get-origin-server-side.ts
This PR will fix bug the `x-forwarded-proto` returns multi protocol `https,http`
> fix: get the first protocol from x-forwarded-proto

- app/_features/home/layout/layout.tsx
- app/_features/room/components/room-actions-bar.tsx
- app/_features/room/components/room-container.tsx
- app/_features/room/components/room-layout.tsx
- app/_features/room/components/room-screen.tsx
- app/_features/room/containers/view-container.tsx
- app/_features/room/styles/room.module.css
This PR adds multiple layouts that support the gallery and presentation layout. For now, it will work automatically whenever there is a presentation screen in the layout; it will switch to the presentation layout. But if there is no presentation screen in the layout, it will use a gallery layout. This also will fix #21
> add multi layout

- app/_features/room/components/conference-participants.tsx
- app/_features/room/components/conference.tsx
- app/_features/room/components/view.tsx
- app/_features/room/styles/conference.module.css
This PR should fix the layout; it must not be scrollable. It should fit into the viewport.
> Multi layout fix

- app/_features/room/components/button-camera.tsx
- app/_features/room/components/button-microphone.tsx
- app/_features/room/contexts/device-context.tsx
This PR is a quick fix to fix the bug label not changing issue when choosing the device
> fix: device selection wrong label

- app/(pages)/room/[roomId]/page.tsx
* Fix the Room ID that was show in Lobby, was showing internal Room ID (Inlive Hub Room ID).
> fix: lobby was showing internal room id

- app/_features/room/components/button-camera.tsx
- app/_features/room/components/button-microphone.tsx
- app/_features/room/components/view.tsx
- app/_features/room/contexts/device-context.tsx
- app/_features/room/contexts/participant-context.tsx
- app/_features/room/hooks/use-select-device.ts
- app/_shared/utils/get-user-media.ts
> fix: device input selection

- app/(server)/_features/participants/repository.ts
- app/(server)/_features/room/service.ts
Reverts inlivedev/inlive-room#60
> Revert "revert: revert the logic for getClientById"

- app/_features/room/contexts/peer-context.tsx
- app/_shared/sdk/room/channel/channel-types.d.ts
- app/_shared/sdk/room/channel/channel.ts
- app/_shared/sdk/room/facade/facade.ts
- app/_shared/sdk/room/peer/peer-types.d.ts
- app/_shared/sdk/room/peer/peer.ts
This PR will change the way sse channel connects. The sse channel will connect when the `PEER_CONNECTED` event is emitted. The sse channel will disconenct when the `PEER_DISCONNECTED` event is emitted
> refactor: client sse channel listens for peer connected and disconnected events

- app/_shared/sdk/room/channel/channel.ts
SSE will reconnect automatically by default. But in case the auto reconnect fails, the manual reconnect should calls every logic that happens on `connect` method.
> fix: ensure the sse reconnect calls everything that happens on connect

- app/_features/home/create-room/create-room.tsx
- app/_features/home/create-room/use-create-room.ts
- app/_features/room/components/button-leave.tsx
- app/_features/room/components/lobby.tsx
- app/_features/room/components/set-display-name-modal.tsx
- app/_features/room/hooks/use-leave-room.ts
This PR will prevent users for clicking the buttons when the (promise) actions have been already executed in order to prevent the duplicate actions by the users.
> fix: prevent double submit when clicking on button

- app/_shared/components/auth/sign-in-modal.tsx
This PR is similar to this https://github.com/inlivedev/inlive-room/pull/66. This will disable sso auth button when clicked.
> fix: disable auth button when clicked

- app/_features/home/create-room/create-room.tsx
- app/_features/room/components/lobby.tsx
This PR will revert and use on click trigger instead of on submit to execute the action
> fix: on click instead of on submit

- app/_shared/hooks/use-viewport-height.ts
This PR will make the`setViewportHeight` running for each resize event with additional debounce technique
> fix: handle setViewportHeight on resize with debounce

- app/_features/home/create-room/create-room.tsx
- app/_features/room/components/conference-actions-bar.tsx
- app/_features/room/components/conference-participants.tsx
- app/_features/room/styles/conference.module.css
- app/_shared/utils/has-touch-screen.ts
- Screen sharing button is displayed only when the device is not a touch screen device. We consider touch screen device as a mobile device for now
- Fix the user camera screen mirroring. Previously, this mirroring is not working when the screen sharing is active.
- Update copywriting on homepage
> fix: style and copywriting improvement

- app/(server)/api/room/[roomID]/setname/[clientID]/route.ts
- app/_shared/middlewares/room.ts
- app/_shared/sdk/room/api/api.ts
- package-lock.json
- package.json
- Use nanoid library to generate random id for client name. It's fine if there is a collision
- Every time the user reload the page, the guest generated name will be different
- When the user has logged in, the name will be same as user account name
- When the user set the display name, it will take priority over account name and generated name
> fix: update the how the client name is generated for guest

- app/_shared/sdk/room/channel/channel.ts
- app/_shared/sdk/room/peer/peer.ts
This PR will fix the client name sometimes not displayed issue
> fix: client name sometimes not displayed

- app/_features/room/styles/conference.module.css
This will temporarily fix the one on one ratio width is too small on mobile
> fix: style mobile ratio fix

- app/(pages)/event/[eventID]/page.tsx
- app/(server)/_features/event/service.ts
- app/(server)/api/_index.ts
- app/_features/event/components/event-detail.tsx
- app/_shared/types/event.d.ts
This PR will make the detail event page dynamic and integrated with the API to get a specific event data.
> feat: dynamic detail event page

- app/(pages)/event/[eventID]/registration-success/page.tsx
- app/_features/event/components/event-detail.tsx
- app/_features/event/components/event-registration-modal.tsx
- app/_features/event/components/event-registration-success.tsx
- app/_features/room/components/lobby.tsx
- app/_shared/components/footer/footer.tsx
- app/_shared/components/header/header.tsx
- app/_shared/types/event.d.ts
This PR will enable the participant to submit and register themselves to the event.
> feat: enable participant to register the event

- app/_features/room/components/button-leave.tsx
- app/_features/room/components/conference-actions-bar.tsx
- app/_features/room/components/conference.tsx
This PR will implement a feature to make everyone leaves from the room at once.
> feat: end room for everyone

- app/_features/room/components/conference-screen.tsx
This PR is a fix to make the remove participant button will only be displayed for participant camera screen only
> fix: remove participant screen only

- app/_features/event/components/event-detail.tsx
- app/_features/room/components/invite-box.tsx
- app/_shared/components/icons/check-icon.tsx
- app/_shared/components/icons/copy-outline-icon.tsx
Update the copy link design when the button is clicked for lobby and detail event pages
Remove "about this event" heading from detail event page
> feat: copy link design update

- app/(pages)/event/[eventID]/page.tsx
- app/(pages)/room/[roomID]/not-found.tsx
- app/not-found.tsx
- Add more meta data information for event detail page.
- Add meta data information for not found page.
> feat: meta data update

- app/(pages)/room/[roomID]/page.tsx
- app/_features/room/components/conference-screen.tsx
- app/_features/room/components/conference.tsx
- app/_features/room/components/view.tsx
- app/_features/room/contexts/metadata-context.tsx
- Make sure moderator feature is displayed again from moderator side
- Set as speaker only displayed when room type is event
- Connection status overlay is not displayed for now
> fix: moderator feature not displayed

- app/_features/room/components/conference-exit.tsx
- app/_features/room/components/conference-lobby.tsx
- app/_features/room/components/lobby.tsx
- app/_features/room/components/view.tsx
- app/_features/room/contexts/client-context.tsx
This PR adds a simple exit room UI. Exit room UI will be displayed when a user leave the room by using the button or when they are forced to leave the room. The UI will not be displayed when the user leave the room by reloading the page.
> feat: exit room UI

- app/(server)/_shared/mailer/mailer.ts
- app/_features/room/components/chat-drawer-menu.tsx
- package-lock.json
- package.json
- Update TypeScript to latest version
- Move mailgun initialization inside function which calls its method
- Remove unused linkify import
> fix:  build error because typescript error complain

- app/(pages)/room/[roomID]/page.tsx
- app/(server)/_features/room/service.ts
- app/_features/room/components/event-container.tsx
- app/_features/room/components/view.tsx
- app/_features/room/contexts/device-context.tsx
- app/_features/room/contexts/peer-context.tsx
- package-lock.json
- package.json
- Update sdk to 0.14.0 which enable to set the codec and bitrate configurations received from room API.
- Revert package-lock.json change. Previously, all dependencies were updated which caused type build error.
- Refactor and move mute mic when entering the room functionality to device context to ensure the user is muted properly.
- Fix `enableVAD` previously only set when creating client and `PERSISTENT_DATA` is not true
> feat: update sdk to 0.14.0 and set codec preference on createPeer

- .env.local.example
- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- app/(server)/api/events/create/route.ts
- app/(server)/api/events/route.ts
- app/(server)/api/room/create/route.ts
- app/_features/home/create-room.tsx
- app/_shared/utils/feature-flag.ts
This PR will implement the feature flag checking for the webinar feature. We will disable webinar features (webinar room and event) for now from the public use. Currently, we only allow some users to access the webinar feature. When the feature is stable enough, we will enable the webinar feature back to the public.
> fix: disable webinar feature as default

- app/_features/home/create-room.tsx
- app/_features/home/home.tsx
- app/_features/home/join-room.tsx
- app/_shared/components/footer/footer.tsx
- package-lock.json
- package.json
- Update copywriting and design for the homepage
- Preparation for webinar beta by:
1. Creating an information alert for the webinar beta after user select to create a webinar room
2. Adding a "limited beta" label on create webinar room dropdown menu
> feat: homepage redesign

- migrations/meta/0011_snapshot.json
- migrations/meta/_journal.json
The previous migration file was not created correctly due to bad merge conflict
> fix: faulty migration was created due to merge conflict

- app/(pages)/event/page.tsx
- app/(server)/_features/event/repository.ts
- app/(server)/_features/event/service.ts
- app/(server)/api/events/route.ts
- app/_features/event/components/event-card.tsx
- app/_features/event/components/event-list.tsx
- app/_features/event/components/event-status.tsx
- app/_shared/components/header/profile.tsx
- app/_shared/components/icons/edit-icon.tsx
- app/_shared/types/event.d.ts
- app/_shared/types/types.d.ts
PR for the event list page add `My Events` menu on the Profile Dropdown and a new Page to browser user created event
This PR is a split feature from #141 to minimize the amount of code changes
> feat: list event page

- app/_features/room/components/conference-lobby.tsx
Changelog : 
* Added message when the room is not ready and being prepared
* Auto refreshes the lobby page when the room is not ready every 5 seconds
> feat: added message & auto refresh when the room is not ready

- app/_features/room/components/conference-screen.tsx
- app/_features/room/contexts/participant-context.tsx
- app/_features/room/contexts/peer-context.tsx
- app/_features/room/hooks/use-screen-share.ts
This PR cleans up some variables
> refactor: variables clean up

- app/(pages)/past-events/page.tsx
- app/_features/event/components/event-list.tsx
- app/_features/event/components/past-events.tsx
- app/_features/event/components/tab-navigation.tsx
- Add UI for past events page
- Add tab navigation page component
- Event list page use tab navigation page component
> feat: past events page

- app/(pages)/event/[eventID]/page.tsx
- app/(server)/api/events/[slugOrId]/route.ts
- app/_features/event/components/event-card.tsx
- app/_features/event/components/event-detail.tsx
- Remove participant limit label
- Update meta title and description on detail page
> fix: fix issues

- app/_features/event/components/event-card.tsx
- app/_features/event/components/event-detail.tsx
- app/_features/event/components/event-registration-modal.tsx
- app/_features/event/components/event-registration-success.tsx
- app/_features/event/components/event-stat-card.tsx
Change time format to en-US with hour `numeric`, minutes `2-digit`, and hour12 `true`
> fix: change time format

- app/_features/home/create-room.tsx
- app/_shared/components/header/profile.tsx
- Add beta info on my events dropdown navigation link
- Remove create webinar room option on homepage
> feat: beta webinar update

- app/(pages)/events/[eventID]/edit/page.tsx
- app/(pages)/past-events/page.tsx
- app/_shared/components/errors/http-error.tsx
- Fix the header sign in button is not responding when the non-login or unauthorized user clicks the button
- Display a "sign in to your account" CTA button instead of "go to the front page" link when non-login user visits the protected route.
> fix: broken sign in button on unauthorized user

- app/(pages)/events/[eventID]/edit/page.tsx
- app/(pages)/events/[eventID]/page.tsx
- app/(pages)/events/create/page.tsx
- app/(pages)/events/page.tsx
- app/(pages)/past-events/page.tsx
- app/_features/event/components/event-detail.tsx
- app/_features/event/components/event-form.tsx
- app/_features/event/components/event-list.tsx
- app/_features/event/components/event-registration-success.tsx
- app/_features/event/components/event-stat-list.tsx
- Change inLive Event logo to inLive Room that will redirect to root page
- Change inLive Event meta title to inLive Room
> fix: change inlive event title and logo back to inlive room

- app/_features/event/components/event-detail.tsx
- app/_features/event/components/event-form.tsx
- app/_features/event/components/event-list.tsx
- app/_features/event/components/event-registration-success.tsx
- app/_features/home/create-room.tsx
- app/_features/home/home.tsx
- app/_features/room/components/conference-exit.tsx
- app/_shared/components/auth/sign-in-modal.tsx
- app/_shared/components/errors/http-error.tsx
- app/_shared/components/header/header.tsx
- app/_shared/components/header/profile.tsx
- Move the events link from profile dropdown to the header
- Adjust the page max width layout to 1280px for every pages except the lobby view.
> feat: events link on header

- app/(server)/_features/event/repository.ts
Fixed the my events page would query soft deleted event
> fix: query should filter out soft deleted events

- app/(pages)/events/[eventID]/detail/page.tsx
- app/(pages)/events/[eventID]/page.tsx
- app/(pages)/events/[eventID]/registration-success/page.tsx
- app/_features/event/components/event-card.tsx
- app/_features/event/components/event-detail-dashboard.tsx
- app/_features/event/components/event-detail.tsx
- app/_features/event/components/event-form.tsx
- app/_features/event/components/event-registration-modal.tsx
- app/_features/event/components/event-registration-success.tsx
- app/_features/event/components/event-stat-card.tsx
- app/_shared/hooks/use-formatted-date.ts
- app/_shared/hooks/use-formatted-datetime.ts
- Add useFormattedDateTime hook which leverages the Intl.DateTimeFormat
- Each date is rendered in the client side to ensure the timezone is the local client timezone.
- Make date format follow similar format.
> fix: fix date error

- app/(server)/_features/event/repository.ts
- app/(server)/_features/event/schema.ts
- app/(server)/_features/room/service.ts
- app/(server)/_shared/mailer/mailer.ts
- app/(server)/api/events/[slugOrId]/register/route.ts
- app/(server)/api/events/index.ts
- app/(server)/api/rooms/[roomID]/register/route.ts
- app/_shared/middlewares/room.ts
- migrations/0021_remove_joinID.sql
- migrations/meta/0021_snapshot.json
- migrations/meta/_journal.json
remove the joinID parameter, and use the clientID directly
> refactor: remove joinID

- app/(pages)/rooms/[roomID]/page.tsx
- app/(server)/_features/room/service.ts
- app/_features/room/components/view.tsx
- app/_features/room/contexts/peer-context.tsx
- package-lock.json
- package.json
There is a breaking change on the API to have more consistent API response on the room endpoint. We have [a PR to adapt the SDK ](https://github.com/inlivedev/inlive-js-sdk/pull/101) and this PR still need to update the SDK version after that PR is merged.
> adapt with the api

- app/(server)/api/rooms/[roomID]/route.ts
- app/_shared/middlewares/room.ts
- package-lock.json
- package.json
- Fix room not found when using non persistant mode
- Update SDK to fix setCodecPreference issue
> fix routing and update SDK

- app/_features/room/components/conference-screen.tsx
- app/_features/room/contexts/datachannel-context.tsx
- app/_features/room/contexts/participant-context.tsx
- package-lock.json
- package.json
This should add voice activity indicator to remove participant video. The indicator will be a green border box on each video that currently has voice activity. 
There is a block of code in participant context that preserve to reorder the participant video based on the top 3 last voice activity. This will implement later.
> feat: add voice actvity indicator on the participant video

- app/_shared/contexts/auth.tsx
This will refactor the auth context. We don't need useState logic inside the context
> refactor: remove user state

- app/_features/room/components/ conference-notification.tsx
- app/_features/room/components/conference-screen.tsx
- app/_features/room/components/conference.tsx
- app/_features/room/contexts/participant-context.tsx
- Pinned icon is displayed for user who pins a participant
- Spotlight icon is displayed for everyone after user spotlights a participant
- Participant who is currently spotlighted will see a message box in their screen to ensure they know when they are currently spotlighted for everyone.
- Fix only host can access spotlight for everyone feature
- Remove participant now only accessible through dropdown participant menu
> feat: icon and notification for spotlight and pin

- app/_features/home/create-room.tsx
- app/_features/meeting/schedule-form.tsx
Fixes:
- Dropdown should only be displayed when there is a user
- Adjust schedule cta button style
> fix: fix create room cta on homepage

- app/_features/room/components/conference-actions-bar.tsx
- app/_features/room/components/conference-top-bar.tsx
- app/_features/room/components/conference.tsx
- app/_features/room/components/participant-list-menu.tsx
- app/_features/room/components/right-drawer-menu.tsx
This PR will add a new menu called participant list menu where the user can see a list of all participants in the room
> feat: participant list menu

- app/_features/room/components/conference-screen.tsx
- app/_features/room/components/participant-dropdown-menu.tsx
- app/_features/room/components/participant-list-menu.tsx
- app/_features/room/components/participant-more-dropdown.tsx
- app/_features/room/contexts/participant-context.tsx
- app/_shared/styles/tailwind.css
This PR will add a new feature which called "Fullscreen view". Now, user can view a single participant in fullscreen mode. This feature is available for everyone in the room and accessible through participant dropdown menu.
> feat: view stream in fullscreen mode

- app/_features/room/components/conference-screen.tsx
Changelogs:
- Adjust pin and spotlight icons indicator position and design
- Adjust participant name design
> fix: adjust pin and spotlight icons indicator position and design

- app/_features/home/not-signed-in.tsx
- app/_shared/components/footer/footer.tsx
- app/_shared/styles/tailwind.css
- Footer update with additional links
- Add learn more on the right side of primary cta
- Add copywriting content about how user can use inlive room as starter template
> feat: home landing page update

- app/_features/home/not-signed-in.tsx
- app/_shared/components/icons/tabler-external-icon.tsx
- Landing page section above footer is updated
> feat: update landing page section above footer

- app/_features/home/not-signed-in.tsx
- public/images/landing/net-pattern.svg
Add simple background pattern for inlive room repo cta in the landing page
> feat: add net pattern as background pattern for inlive room repo cta

- app/_features/room/components/conference-screen.tsx
This should fix voice activity sometimes is not update the visual indicator when a video has voice activty.
> fix voice activity

- app/(server)/api/events/[slugOrId]/calendar/[participantId]/route.ts
- app/(server)/api/events/[slugOrId]/client/route.ts
- app/(server)/api/events/[slugOrId]/details/registeree/route.ts
- app/(server)/api/events/[slugOrId]/route.ts
Fix bad query on events with an emoji
> fix: bad query slug with emoji

- app/(server)/_features/event/repository.ts
- app/(server)/_features/event/schema.ts
- app/(server)/_features/event/service.ts
- app/(server)/_features/scheduled-meeting/service.ts
- app/(server)/api/scheduled-meeting/route.ts
- emails/event/EventScheduleMeetingCancelled.tsx
Feat: Added Scheduled Meeting Method to Update Existing Meeting
> feat: update email endpoint

- app/(server)/_features/room/service.ts
- app/(server)/api/rooms/[roomID]/route.ts
Changelog : 
* Rewrite the `joinRoom()` function better readability 
* Added exported const `Revalidate:0` ensuring no caching and endpoint revalidated
* Added typing into the SDK variable, for better DX
https://github.com/inlivedev/inlive-room/blob/47bfc85c24415bab55018dd955b3985769dfc82c/app/(server)/_features/room/service.ts#L38
> fix: attempt to fix the sdk.create room was not called
