inlivedev/inlive-room

app/_features/room/components/room-actions-bar.tsx
app/_features/room/components/room-container.tsx
app/_features/room/components/room-layout.tsx
app/_features/room/modules/factory.ts
app/_features/room/modules/media.ts
app/_features/room/modules/room.ts
app/_features/room/types/types.d.ts

This update follows the latest update from inLive Hub API changes that change how clients publish and subscribe to the track to identify the track source, whether it is a media device or screen sharing. The video container will have a specific `media` or `screen` class name on their div container. This will differentiate and allow us to put the screen-sharing video on a bigger layout ratio when there is a screen-sharing video in the room.

add track source type

---

.env.local.example
app/(server)/api/auth/[provider]/authenticate/route.ts
app/(server)/api/auth/[provider]/authorize/route.ts
app/_shared/components/auth/sign-in-modal.tsx

- Fix successful auth redirect should be based on previous user path before user tries to authorize themselves
- `NEXT_PUBLIC_APP_ORIGIN` example use localhost by default

fix: success auth redirect should be based on previous path

---

app/_features/room/components/button-camera.tsx
app/_features/room/components/button-microphone.tsx
app/_features/room/components/view.tsx
app/_features/room/contexts/device-context.tsx
app/_features/room/hooks/use-select-device.ts
app/_features/room/hooks/use-video-screen.ts

- Fix the speaker selection doesn't get displayed on mobile device.
- When the user device doesn't support `setSinkId` method from [MediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) and [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/setSinkId). The speaker selection only display the current speaker.

fix: device output selection

---

app/(server)/_features/participants/schema.ts
migrations/0004_client_id_unique-per-room.sql
migrations/meta/0004_snapshot.json
migrations/meta/_journal.json

* Following inlive hub, client-id should be only unique per room-id
* participants table now uses composite primary key room_id and client_id

fix: client-id should be unique per room-id

---

app/_features/home/view/view.tsx
app/_features/room/components/chat-drawer-menu.tsx
app/_features/room/components/conference-actions-bar.tsx
app/_features/room/components/conference-screen.tsx
app/_features/room/components/conference.tsx
app/_features/room/components/lobby.tsx
app/_features/room/components/view.tsx
app/_features/room/styles/conference.module.css
app/_shared/components/containers/app-container.tsx
app/_shared/components/errors/http-error.tsx
app/_shared/hooks/use-viewport-height.ts
app/_shared/styles/tailwind.css
app/layout.tsx

- Every views use `min-viewport-height` class name to set default minimum height is same with minimum viewport
- For conference room view will use `viewport-height` and add little calculations to calculate the actual viewport height on mobile. This will ensure the mobile screen will always full height screen.
- Add mirroring style to local video
- Add z index to overlay to fix the participant name covered by the video element

fix: improve mobile height style

---

app/_features/room/components/button-camera.tsx
app/_features/room/components/button-microphone.tsx
app/_features/room/components/event-container.tsx
app/_features/room/components/view.tsx
app/_shared/utils/has-touch-screen.ts

This PR will adjust the behavior when the user off the page window on mobile. On mobile, when the user off the page, the webrtc will not stream the video and audio tracks to the remote users. This makes the video on remote users will be freezed. One way to handle this is to make the user camera and audio tracks auto muted when the user off the page window on mobile.
I thought we could achieve this by listening the [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event and checked if the [visibilityState](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState) was hidden. However, I didn't understand why the callback for visibilitychange `hidden` only called when the document had been active again, the callback didn't …

fix: handle when the user off the page window on mobile

---

app/_features/room/hooks/use-leave-room.ts
app/_shared/sdk/room/api/api.ts

- Update leave room SDK and return the same response object when either using sendBeacon or regular fetch
- Refactor the useLeaveRoom function. The leaveRoom method will not be called useBeacon and use regular fetch instead

refactor: leave room

---

app/(server)/api/auth/[provider]/authenticate/route.ts
app/(server)/api/room/[roomID]/setname/[clientID]/route.ts

- token and client name cookies are set to expire after 30 days

feat: use max age for cookie

---

.vscode/settings.json
app/(pages)/room/[roomID]/page.tsx
app/(server)/_shared/auth/auth.ts
app/_features/room/components/button-leave.tsx
app/_features/room/components/button-microphone.tsx
app/_features/room/components/button-screen-share.tsx
app/_features/room/components/conference-actions-bar.tsx
app/_features/room/components/conference-presentation-layout.tsx
app/_features/room/components/conference-screen-hidden.tsx
app/_features/room/components/conference-screen.tsx
app/_features/room/components/conference-speaker-layout.tsx
app/_features/room/components/conference.tsx
app/_features/room/components/meeting-gallery-layout.tsx
app/_features/room/components/meeting-one-on-one-layout.tsx
app/_features/room/components/meeting-presentation-layout.tsx
app/_features/room/components/view.tsx
app/_features/room/contexts/metadata-context.tsx
app/_features/room/styles/meeting-gallery-layout.css
app/_features/room/styles/meeting-presentation-layout.css

In this PR, we put back the meeting room layout again. However, in the future when creating a room, there will be an option to create a room for meeting or create a room for webinar event. The current implementation will use meeting room layout as default layout. The meeting room preset is back that consists of gallery, one on one, and presentation layouts.
All participants are able to mute and unmute again. However, the first time user joins, they will be automatically muted. All participants are also rendered, even when they are not currently displayed on the screen. So, everyone is able to hear anyone voice when they unmute the mic.

feat: meeting and webinar layouts

---

app/_features/room/components/conference-actions-bar.tsx
app/_features/room/components/conference-screen.tsx
app/_features/room/components/conference-top-bar.tsx
app/_features/room/components/conference.tsx
app/_features/room/components/gallery-layout.tsx
app/_features/room/components/meeting-one-on-one-layout.tsx
app/_features/room/styles/gallery-layout.css
app/_features/room/styles/meeting-presentation-layout.css
app/_features/room/styles/webinar-presentation-layout.css
app/_features/room/styles/webinar-speaker-layout.css

- Add topbar in the room
- Put connection status on the left side of topbar
- Put the mode/view selection on the right side of topbar. View selection can only be viewed by moderator and only available for webinar room. Moderator can select between speaker or gallery views.
- Add total participant count on the right side of topbar. This is available on every room.
Additional:
- Remove alert confirmation when setting a user to speaker or regular participant.
- Moderator cannot set themselves to regular participant.
- When in the gallery mode, moderator cannot set anyone to speaker or regular participant. In the gallery mode, everyone is on the equal stage.

feat: add top bar and gallery layout options to the webinar room

---

app/(pages)/event/[eventID]/edit/page.tsx
app/(pages)/event/create/page.tsx
app/(pages)/event/page.tsx
app/_shared/components/errors/http-error.tsx
app/_shared/components/header/profile.tsx

- My Events menu will display "Limited Beta" when the webinar is only enabled for specific users. For users who are part of early access, the menu is disabled.
-  When the webinar is only enabled for specific users, only early access users will be able to access `/event` page. The metadata was also adjusted and updated.
- When the webinar is only enabled for specific users, only early access users will be able to access `/event/create` page. The metadata was also adjusted and updated.
- Ensure `/event`, `/event/create`, and `/event/{id}/edit` pages are only accessible for logged in users.
- Updated the `/event/{id}/edit` metadata

feat: event pages for early access users

---

app/_features/room/components/conference-screen.tsx

- Performs the cleanup when the video component unmount from the screen.
- Separate video element mounting and unmounting logic from the conference screen component
- Video is played after `loadedmetadata` is triggered

fix: clean up when video screen unmounted from the screen

---

app/(pages)/past-events/page.tsx
app/_features/home/create-room.tsx
app/_features/home/home.tsx
app/_shared/components/header/profile.tsx

- My event navigation link is not restricted by beta
- Remove restriction on creating the webinar room from the homepage.
- Remove alert information about webinar with limited early access

fix: remove limiting the webinar access to some pages

---

app/_features/home/create-room.tsx
app/_shared/components/header/profile.tsx

This PR will revert and display the create webinar room option when the user triggers the create room dropdown again after being removed previously. It also displaying the beta info again besides the create webinar room option.

revert: revert displaying create webinar room option

---

app/(server)/_features/event/repository.ts
app/(server)/api/events/[slugOrId]/details/registeree/route.ts

Created endpoint `GET` `/api/events/:id/details/registerees`
Represent the Count & List of registered participants on a particular event. The endpoint is only available to the event creator. A registeree is added when a user register to an event.
[Response Detail](https://docs.google.com/document/d/1SkyQl1-p1S08y0TTXBc62J8POUg98dRPjOo9WkA3EOI/edit)

feat: endpoint to get registered participants

---

app/(server)/api/events/[slugOrId]/stat/route.ts
app/_features/event/components/event-list.tsx
app/_features/event/components/event-stat-card.tsx

- NaN percentage value will be considered as zero percentage
- Display postfix percentage symbol
- Past events page navigation link now accessible from my events page
- Remove link to detail page of each past event card for now.

fix: fixing NaN percentage value on past events stat

---

app/(pages)/past-events/[eventID]/page.tsx
app/(server)/api/events/[slugOrId]/stat/route.ts
app/_features/event/components/event-past-dashboard.tsx
app/_features/event/components/event-stat-card.tsx
app/_features/event/components/event-stat-list.tsx
app/_shared/components/icons/info-icon.tsx
app/_shared/types/event.d.ts

Added new page `past-events/<evenSlug>` to view past-events detail
user can view all participant and a more detailed stats

feat: new page to show past-event detail

---

app/_features/room/contexts/participant-context.tsx

This PR will fix the issue about new participant layout didn't change when the "spotlight for everyone" event has arrived before the participant joins to the room

fix: new participant doesn't know whether a stream is spotlighted or not when the event has been emitted earlier

---

app/(server)/_shared/utils/sdk.ts
package-lock.json
package.json

- Accomodate SDK change based on [this PR](https://github.com/inlivedev/inlive-js-sdk/pull/113) and following the newer initialization with create auth module. This change only happens on server side SDK because the client side one still doesn't need auth mechanism.
- Updated drizzle kit to 0.23.0 because 0.21.1 complained and asked for update.

chore: update inlive-js-sdk to 0.19.1

---

app/_features/room/components/button-camera.tsx
app/_features/room/components/button-microphone.tsx
app/_features/room/contexts/device-context.tsx
app/_features/room/hooks/use-select-device.ts
package-lock.json
package.json

- Fix device selection option doesn't show up on safari
- Default device selection option label when a specific device type is not available (such as speaker), but it actually exists.
- Update @nextui-org/react to 2.4.6

fix: device selection option doesn't show up on safari

---

app/_features/room/components/button-camera.tsx
app/_features/room/components/button-microphone.tsx
app/_features/room/components/event-container.tsx
app/_features/room/contexts/device-context.tsx
app/_features/room/hooks/use-select-device.ts

- Fix issue about switching mic and camera devices on mute turning on the video and audio to other users. Now, switching mic and camera still retains the mute state and when the unmute button is clicked, user will use the new device.
- Refactor the logic to use context state for listening on/off camera and mic instead of using custom event.

fix: switching mic and camera devices on mute turning on the video and audio to other users

---

app/_features/room/components/conference-top-bar.tsx
app/_features/room/components/participant-dropdown-menu.tsx
app/_features/room/contexts/metadata-context.tsx

We have decided that the webinar and meeting experiences should be the same. For now, we plan to make the layout between the webinar and meeting rooms are similar.
- Default layout for webinar room is gallery layout.
- Remove dropdown view selection which changes to gallery or stage layouts. In the future, stage layout should be based on multiple spotlights.
- Remove set speaker and set regular participant dropdown options.

refactor: make webinar room experience same with meeting room

---

app/(server)/_features/event/repository.ts
app/(server)/_features/event/service.ts
app/(server)/_features/room/service.ts
app/(server)/api/rooms/[roomID]/route.ts
app/_shared/middlewares/room.ts
app/_shared/types/room.d.ts

This PR Update the Room Middleware allowing Event Room for `scheduled meeting` to be joinable without clientID

feat: rewrite middleware for scheduled-meeting allow no clientID
